package id.my.sendiko.fintrack.core.presentation

import androidx.compose.runtime.Composable
import org.jetbrains.compose.resources.StringResource
import org.jetbrains.compose.resources.getString
import org.jetbrains.compose.resources.stringResource

sealed class UiText {
    /**
     * Represents a simple, dynamic string value that doesn't need localization.
     */
    data class DynamicString(val value: String) : UiText()

    /**
     * Represents a localizable string from Compose Multiplatform's resource system.
     *
     * @param id The [StringResource] identifier generated by the CMP resources library.
     * @param args Optional arguments for formatting the string resource.
     */
    data class CmpStringResource(
        val id: StringResource,
        val args: List<Any> = emptyList()
    ) : UiText()

    /**
     * Resolves the UiText to a raw String within a Composable context.
     *
     * This is the idiomatic way to display a UiText value in your UI.
     *
     * @return The resolved string.
     */
    @Composable
    fun asComposableString(): String {
        return when (this) {
            is DynamicString -> value
            is CmpStringResource -> stringResource(id, *args.toTypedArray())
        }
    }

    suspend fun asString(): String {
        return when (this) {
            is DynamicString -> value
            is CmpStringResource -> getString(resource = id, *args.toTypedArray())
        }
    }
}